FROM node:22-alpine
WORKDIR /usr/src/app
ARG DATABASE_URL
COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web
RUN npm  install
RUN cd apps/web && npm run build
EXPOSE 3000
CMD [ "npm ", "run" ,"start:web" ]